au-ts/cogent

cogent/COGENT/Desugar.hs, cogent/COGENT/DocGent.hs, cogent/COGENT/Parser.hs, cogent/COGENT/PrettyPrint.hs, cogent/COGENT/Surface.hs, cogent/COGENT/TypeCheck/Base.hs, cogent/COGENT/TypeCheck/Generator.hs, cogent/COGENT/TypeCheck/Post.hs, cogent/COGENT/TypeCheck/Solver.hs, cogent/tests/pass_case-default-constructor.cogent, cogent/tests/pass_case-default.cogent, cogent/tests/pass_case-literal-default.cogent, cogent/tests/pass_unboxed-rec-subtyping.cogent, cogent/tests/pass_useability-in-default.cogent
Implementing the revamped subtyping that should eliminate a lot of redundant copies.
It currently fails two tests with leftover constraints. Still working on why that is the case. It may be WAD, in which case we'll have to see how it goes on real programs before deciding if we want to start guessing types to fix constraints.
`Widen` has been removed, too. 
You can now use `take` and `put` to take/put fields from records AND tags from variants.
The desugarer has just been hacked so it will compile. It may not work correctly. I left TODO tags.
=> Cogent 2.1

build-env.mk, impl/bilby/cogent/Makefile, impl/ext2/cogent/Makefile, impl/skel-fs/cogent/Makefile, impl/skel-fs/cogent/data/README.md, impl/skel-fs/cogent/plat/linux/module.c, impl/skel-fs/cogent/plat/linux/wrapper.ac
Add entry and exit functions to the various `super_block`, `file_operations`
and `inode_operations` structures.
The idea is to provide a framework of sorts that can be used to implement an
actual filesystem, by implementing the missing pieces, with the grunt work
already done.
This commit also adds support for verbose mode for Makefiles.
=> [skelfs] Skel-fs framework.

cogent/cabal.project, cogent/cogent.cabal, cogent/src/Cogent/CodeGen.hs, cogent/src/Cogent/Compiler.hs, cogent/src/Cogent/Desugar.hs, cogent/src/Cogent/Glue.hs, cogent/src/Cogent/Mono.hs, cogent/src/Cogent/MonoProof.hs, cogent/src/Cogent/Normal.hs, cogent/src/Cogent/PrettyCore.hs, cogent/src/Cogent/ProofGen.hs, cogent/src/Cogent/Shallow.hs, cogent/src/Cogent/Simplify.hs, cogent/src/Cogent/Sugarfree.hs, cogent/src/Cogent/TypeProofs.hs, cogent/src/Cogent/Vec.hs, cogent/src/Data/Monoid/Cancellative.hs
This patch contains the following changes:
* Drop monoid-subclasses as a dependency because it is really broken in 8.0
and has lots of orphans.
* Made a number of Fin types more accurate.
* Remove GHC < 8.0 conditional error branches that allegedly aren't needed in
8.0.
* Fixed some goodly numer of Ticked Constructor warnings
* Trimmied trailing whitespace noise.
=> [compiler] GHC 8.0 support and other fixes.

cogent/lib/cogent-defns.h, cogent/scripts/cogent_validate.sh, cogent/src/Cogent/CodeGen.hs, cogent/tests/cogent.h, impl/bilby/cogent/plat/verification/wrapper.ac, impl/ext2/cogent/plat/verification/wrapper.ac
`cogent-defns.h` is a much more appropriate name. Also remove the duplicate
`cogent.h` in `tests`.
=> Rename cogent.h to cogent-defns.h

cogent/cogent.cabal, impl/bilby/cogent/src/ubi.cogent
I had accidentally assumed that buffer.cogent was in `gum/kernel/linux`
instead of `gum/common`. This patch fixes that mistake.
=> Include the proper path for buffer.cogent.

impl/bilby/cogent/plat/linux/rbt.c, impl/bilby/cogent/plat/linux/wrapper.h, impl/bilby/cogent/src/bilbyfs.cogent
Another attempt to making sure that the regression tests pass.
=> Fix the include path for cogent files in bilby.

cogent/lib/c/linux/abstract-defns.h, cogent/lib/gum/anti/bufferhead.ac, cogent/lib/gum/common/common.cogent, cogent/lib/gum/kernel/linux/bufferhead.cogent
We currently have `OSBuffer`(in osbuffer.cogent and osbuffer.ac) which is
a wrapper over `struct buffer_head`. This patch creates a new
implementation called `BufferHead`, which reflects the name of the actual
structure in the Linux kernel. And also cleans up the current
implementation.
I've created new files for this implementation (`bufferhead.cogent` and
`bufferhead.ac`) and retaining the old implementation until we transition
over to the new implementation everywhere.
This patch also adds:
* `SysState` to `common.cogent`, which is the eventual replacement for
`ExState`. We are still retaining `ExState` until we make sure that
transition has occured smoothly.
* Created a common `abstract-defns.h` file in `lib/c/linux` - this file
is going to hold the definitions of all the abstract …
=> [libgum] Some methods to access struct buffer_head

cogent/lib/gum/kernel/linux/bufferhead.cogent
There signature of the `buffer_head_find` function has an error. And
this patch fixes that.
=> [libgum] Fix the signature of buffer_head_find.

cogent/lib/gum/anti/os.ac, cogent/lib/gum/kernel/linux/os.cogent
This patch adds Cogent wrappers for `spin_lock` and `spin_unlock`. We also
remove a `FIXME` in `os.cogent`.
=> [libgum] Wrappers for spin_lock and spin_unlock.

cogent/lib/gum/anti/bufferhead.ac, cogent/lib/gum/kernel/linux/bufferhead.cogent
Currently `buffer_head_read_block` function expects a rw `VfsSuperBlock`,
but that shouldn't be the case as we don't/shouldn't modify the super block
in that function. This patch makes that change.
=> [libgum] BufferHead api changes.

cogent/lib/gum/common/common.cogent
The commit `ead63ccc60da6b8adebeeafb94d8d2cd8cb0f83b` breaks the build
because of the duplicate `type SysState` declaration.
=> [libgum] Remove duplicate `SysState` declaration.

impl/fs/bilby/proof/ROOT, impl/fs/bilby/proof/lib/L4vBucket.thy, impl/fs/bilby/test/regtest
There's a regression because of commit dc6bd0fb4d1538a9bc11a68679abaf8e3f6b3362
and this patch fixes that.
=> [bilby] Fix bilby typecheck tests.

.travis.yml, cogent/cogent.cabal
* use multi-ghc-travis template
* also add file systems builds in the CI
* tried the new nix-style cabal: DOES'T WORK
- it needs all files added to the .cabal file,
- which means for us all libgum
* tried without a sandbox: DOESN'T WORK
- we need to deal with isa-parser separately and
- I don't see a clean way of doing it
* use multiline syntax in the yml file
* make ghc-8.0.2 allow_failure, it currently fails
due to upstream problems
* use jobs: 2 in cabal.config file
* fix directory due to impl reorg
=> travis: cache the entire sandbox

cogent/cogent.cabal
these modules need to be exported for cogent to be included as a library dependency.
=> Export autogen modules so package can be used as a dependency

README.md, cogent/isa/Cogent.thy
The main difference between here and 354f7bc is that I changed the typing_prom rule to have
∀c t b. (c,t,b) ∈ set ts ⟶ (∃b'. (b' ⟶ b) ∧ ((c,(t,b')) ∈ set ts'))
instead of
(c,t,b) ∈ set ts ⟶ ((c,t,b') ∈ set ts' ∧ (b' ⟶ b))
I believe this is justified, since the old one is essentially the same as
∃c t b b'. (c,t,b) ∈ set ts ⟶ ((c,t,b') ∈ set ts' ∧ (b' ⟶ b))
which presumably is not what we want
=> proof: fix the proofs in Cogent.thy

cogent/src/Cogent/Inference.hs, cogent/tests/pass_subtyping-con-promote.cogent
@zilinc @liamoc 
My understanding of the Core type system is that all subtyping requires
an explicit Promote term. I believe there is no implicit subsumption.
In the formalisation, the rule for variants is something like the following, and it requires
the expression type to be *strictly equal* to the type for the tag in the
variant type:
```
... |-  e : ts[tag]
---------------------------------
... |-   Con tag e ts : TSum ts
```
However, the compiler is currently generating core code that allows subtyping
underneath a Con, which would correspond to something like the following rule:
```
... |-  e : t'           t' <= ts[tag]
----------------------------------------
... |-   Con tag e ts : TSum ts
```
I think this is just a bug in the implementation of `infer`, as it was
not adding …
=> compiler: core/infer: insert Promote terms underneath Con

cogent/isa/Cogent.thy, cogent/isa/Correspondence.thy, cogent/isa/Subtyping.thy, cogent/isa/UpdateSemantics.thy, cogent/isa/Util.thy, cogent/isa/ValueSemantics.thy
Add subtyping to formalisation.
The following files in cogent/isa have been updated with subtyping: Cogent, ValueSemantics, UpdateSemantics, and Correspondence. These files go through with no errors.
The following files fail on master and in this branch: Mono, Mono_Tac, CogentHelper, and Subtyping. The files in `shallow/` do not fail immediately, but they haven't been updated with subtyping, so presumably the tactics don't work on programs.
=> Proof of subtyping

cogent/Main.hs, cogent/src/Cogent/C/Compile.hs, cogent/src/Cogent/Common/Syntax.hs, cogent/src/Cogent/Core.hs, cogent/src/Cogent/Desugar.hs, cogent/src/Cogent/Glue.hs, cogent/src/Cogent/Haskell/Shallow.hs, cogent/src/Cogent/Inference.hs, cogent/src/Cogent/Isabelle/CorresProof.hs, cogent/src/Cogent/Isabelle/Deep.hs, cogent/src/Cogent/Isabelle/GraphGen.hs, cogent/src/Cogent/Isabelle/ProofGen.hs, cogent/src/Cogent/Isabelle/Shallow.hs, cogent/src/Cogent/Mono.hs, cogent/src/Cogent/Preprocess.hs, cogent/src/Cogent/PrettyPrint.hs, cogent/src/Cogent/Reorganizer.hs, cogent/src/Cogent/Simplify.hs, cogent/src/Cogent/Surface.hs, cogent/src/Cogent/TypeCheck/Base.hs
Individuate core function names from String. This will eventually lead into type level checking of generated Isabelle names, to make sure they don't start or end with `_`.
=> compiler: individuate the types of function names in core

cogent/cogent.cabal, cogent/isa/shallow/Shallow_Normalisation_Tac.thy, cogent/isa/shallow/Shallow_Tac.thy, cogent/src/Cogent/Inference.hs, cogent/src/Cogent/Isabelle/Compound.hs, cogent/src/Cogent/Isabelle/Shallow.hs, cogent/tests/pass_ex-variants.cogent
We can generate nicer cases. This should make the shallow embeddings a lot smaller and nicer, and fix some of the problems with code explosion in the continuation for cases.
Extended SCorres rule looks something like this:
```
(*
datatype ('a, 'b, 'c) X2 =
KindOfBad "'a"|
Restart "'b"|
SuperGood "'c"
*)
lemma scorres_supercase_X2 :
"scorres x x' γ ξ ⟹ 
(⋀v v'. valRel ξ v v' ⟹ scorres ((if t1 = ''KindOfBad'' then skindofbad else if t1 = ''Restart'' then srestart else ssupergood) (shallow_tac__var v)) d1 (v'#γ) ξ) ⟹ 
(⋀v v'. valRel ξ v v' ⟹ scorres ((if t2 = ''KindOfBad'' then skindofbad else if t2 = ''Restart'' then srestart else ssupergood) (shallow_tac__var v)) d2 (v' # VSum t2 v' # γ) ξ) ⟹ 
(⋀v v'. valRel ξ v v' ⟹ scorres ((if t3 = ''KindOfBad'' then skindofbad else if t3 = ''Restart'' …
```
=> flatten case expressions in shallow embedding

cogent/cogent.cabal, cogent/src/Cogent/Common/Syntax.hs, cogent/src/Cogent/Isabelle/CorresProof.hs, cogent/src/Cogent/Isabelle/Deep.hs, cogent/src/Cogent/Isabelle/IsabelleName.hs, cogent/src/Cogent/Isabelle/MonoProof.hs, cogent/src/Cogent/Isabelle/NormalProof.hs, cogent/src/Cogent/Isabelle/ProofGen.hs, cogent/src/Cogent/Isabelle/Shallow.hs, cogent/src/Cogent/Isabelle/TypeProofs.hs, cogent/src/Cogent/Simplify.hs
Added:
* Shallow proof to renaming
* A few extra places that weren't renamed
* No isabelle unicode symbols in ML
Fixes #300
=> compiler: Fix isabelle renaming to be consistent

impl/fs/bilby/README, impl/fs/bilby/c/bilbyfs.h, impl/fs/bilby/c/fsop.c, impl/fs/bilby/c/os/linux/wrapper.c, impl/fs/bilby/c/ostore.c
-- use 64-bit timespec
-- changed symlink implementation.
-- remove some compiler warnings
-- fix spelling errors.
=> Bilbyfs: C version: Update to Linux kernel after 4.19.

cogent/src/Cogent/Core.hs
fix comments for `ArrayTake` and `Take` in `Expr` inside Core.hs
=> compiler: fix comments

docs/conf.py
RTD seems to be running a fossilised version of Debian (is there any
version of Debian that isn't?), and thus an incomplete TeX Live which
lacks fonts like Libertinus (which apparently only appeared in 2018).
For bonus points, RTFD only use pdfLaTeX.  *sigh*
[skip ci][skip lemma]
=> docs: Work around breakage in Read The Docs' PDF rendering.

cogent/src/Cogent/TypeCheck/Solver/SinkFloat.hs, minigent/src/Minigent/TC/Simplify.hs, minigent/src/Minigent/TC/SinkFloat.hs
* SinkFloat now propagates record subtyping the right way (taken is pushed *up*, untaken is pushed *down*)
=> Sink float fix

c-refinement/Cogent_Corres.thy, c-refinement/Cogent_Corres_Shallow_C.thy, cogent/isa/Correspondence.thy, cogent/isa/UpdateSemantics.thy, cogent/src/Cogent/Isabelle/AllRefine.hs
This fixes the abstract typing relation in the update semantics and the value relation between the update and value semantics for abstract types. Both of these relations were broken due to not taking the Cogent heap as an argument.
Before this fix, one could show that all pointers in an abstract value are valid, i.e. point to something, for all Cogent heaps, which is clearly incorrect.
With these fixes, an additional constraint on abstract types is required, i.e. their values satisfy the frame constraint, in order to prove the uval_typing_frame and upd_val_rel_frame theorems. This addition should not adversely affect Cogent since this constraint is alluded to in "Type Systems for System Types", chapter 4,  subsection "Abstract Values", page 88, …
=> Fixes update abstract typing relation and abstract update value relation
